gText_Birch_Welcome::
	.string "What the hell! Who are you!?\p"
	.string "And why are we both in this dark\n"
	.string "place? Did you kidnapp me?!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Show them what you got Sceptile!{PAUSE 96}\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Wait why did you not take my POKéMON\n"
	.string "away when you kidnapped me?\p"
	.string "You also look a bit young for a dealer.\p"
	.string ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\p"
	.string "So you are saying you are currently\n"
	.string "in the back of a moving truck.\p"
	.string "Next to furniture and other stuff that\n"
	.string "could fall on you?\p" 
	.string "Who puts a damn child in the back\n"
	.string "of a truck?!\p"
	.string ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\p"
	.string "Oh my apologies I did not mean to call\n"
	.string "you a child. I did not know you already\l"
	.string "turned 10, sir ... or madam?\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Excuse my rudeness ...$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "Nice thats my favorite gender.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\p"
	.string "And we are both somehow trapped in this\n"
	.string "dark dimension ...\p"
	.string "Must be Dialga and Palkia shenanigans..\p"
	.string "I hope this time I will not be having a\n"
	.string "seizure right after I get back into\l"
	.string "my body.. sigh\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, I can feel the tingling.\p"
	.string "Have a nice trip in the back of the\n"
	.string "truck and phasing back into your body.\p"
	.string "The feeling of dread and insignificance\n"
	.string "will only last for a few days.\p"
	.string "And by the off chance we meet and I had\n"
	.string "the luck to completely forget about\l"
	.string "this, please do not remind me.\p"
	.string "We still do not fully understand these\n"
	.string "dark dimensions.\p"
	.string "Some studies showed participants not\n"
	.string "remembering anything after such an\l"
	.string "event, just having a slight headache.\p" 
	.string "However, telling them what happened\n"
	.string "triggered seizures and ... other very\l"
	.string "bad things.\p"
	.string "Well its happening I hope we will\n"
	.string "never remember seeing us.\p"
	.string "$"
